---
- name: Restart moondeckbuddy service
  ansible.builtin.systemd:
    name: moondeckbuddy.service
    state: restarted
    scope: user
  become: false
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ cachyos_user_uid }}"
    DBUS_SESSION_BUS_ADDRESS: "unix:path=/run/user/{{ cachyos_user_uid }}/bus"
