---
- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart keyd
  ansible.builtin.systemd:
    name: keyd
    state: restarted

- name: Reload udev rules
  ansible.builtin.command: udevadm control --reload-rules
  changed_when: false
